/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import dao.Ga_dao;
import dao.LichTrinh_dao;
import entity.GaTauEntity;
import entity.LichTrinhEntity;

/**
 *
 * @author ploc2
 */
public class BanVe_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form BanVe_JPanel
     */

    private Ga_dao ga_dao = new Ga_dao();
    private LichTrinh_dao lichTrinh_dao = new LichTrinh_dao();

    public BanVe_JPanel() {
        initComponents();
        setVisible(true);
        setBounds(0, 0, 1186, 748);

        URL image_BanHang = TrangChu_GUI.class.getResource("/pic/icon/buttonTimKiem.png");
        ImageIcon img_BanHang = new ImageIcon(image_BanHang);
        Image scaled_BanHang = img_BanHang.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        img_BanHang = new ImageIcon(scaled_BanHang);
        lbl_IconTimKiem.setIcon(img_BanHang);

        ArrayList<GaTauEntity> dsGaTau = ga_dao.getAllGaTau();
        duaDuLieuVaoComboBox(cbo_GaDi, dsGaTau, "TenGa");
        duaDuLieuVaoComboBox(cbo_GaDen, dsGaTau, "TenGa");

    }

    // Hàm đưa dữ liệu vào combobox
    private void duaDuLieuVaoComboBox(JComboBox comboBox, ArrayList<?> data, String thuocTinh) {
        DefaultComboBoxModel<Object> model = new DefaultComboBoxModel<>();
        for (Object item : data) {
            try {
                Object propertyValue = item.getClass().getMethod("get" + thuocTinh).invoke(item);
                model.addElement(propertyValue);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        comboBox.setModel(model);
    }

    private void jPanel_btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {
        // Lấy dữ liệu từ các thành phần UI
        java.util.Date ngayDi = txt_NgayDi.getDate();
        java.util.Date ngayVe = txt_NgayVe.getDate();
        String gaDi = (String) cbo_GaDi.getSelectedItem();
        String gaDen = (String) cbo_GaDen.getSelectedItem();

        // check maGa
        String maGaDi = ga_dao.layMaGaTheoTen(gaDi);
        String maGaDen = ga_dao.layMaGaTheoTen(gaDen);

        // Kiểm tra xem các trường dữ liệu có hợp lệ hay không
        if (ngayDi == null || gaDi == null || gaDen == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Chuyển đổi ngày thành định dạng mà bạn cần nếu cần thiết
        java.sql.Date sqlNgayDi = new java.sql.Date(ngayDi.getTime());
        java.sql.Date sqlNgayVe = (ngayVe != null) ? new java.sql.Date(ngayVe.getTime()) : null;

        // kiểm tra ngày đi không được ngày hôm nay hoặc quá khứ
        if (sqlNgayDi.before(new java.sql.Date(System.currentTimeMillis()))) {
            JOptionPane.showMessageDialog(this, "Ngày đi không được ngày hôm nay hoặc quá khứ.", "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Gọi phương thức tìm kiếm lịch trình
        ArrayList<LichTrinhEntity> lichTrinhList = lichTrinh_dao.timKiemLichTrinh(maGaDi, maGaDen, sqlNgayDi);

        // Xử lý kết quả trả về (ví dụ: hiển thị kết quả vào bảng)
        if (lichTrinhList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy lịch trình nào.", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            // Giả sử bạn có một phương thức để hiển thị kết quả
            new DatVe_JFrame(lichTrinhList).setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_ChiTietTau = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel_TimKiem = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadio_MotChieu = new javax.swing.JRadioButton();
        jRadio_KhuHoi = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txt_NgayDi = new com.toedter.calendar.JDateChooser();
        txt_NgayVe = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jPanel_btnTimKiem = new javax.swing.JPanel();
        lbl_IconTimKiem = new javax.swing.JLabel();
        btn_TimKiem = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jRadio_ChoNguoi = new javax.swing.JRadioButton();
        jRadio_ChoHang = new javax.swing.JRadioButton();
        cbo_GaDi = new javax.swing.JComboBox<>();
        cbo_GaDen = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        lbl_TimKiemVeTau1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 31, Short.MAX_VALUE));
        panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 31, Short.MAX_VALUE));

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel_ChiTietTauLayout = new javax.swing.GroupLayout(jPanel_ChiTietTau);
        jPanel_ChiTietTau.setLayout(jPanel_ChiTietTauLayout);
        jPanel_ChiTietTauLayout.setHorizontalGroup(
                jPanel_ChiTietTauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_ChiTietTauLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_ChiTietTauLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel_ChiTietTauLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel_ChiTietTauLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel_ChiTietTauLayout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(55, 55, 55)
                                                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(67, 67, 67)
                                                        .addComponent(jLabel3))
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 238,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel_ChiTietTauLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                .addGap(27, 27, 27)));
        jPanel_ChiTietTauLayout.setVerticalGroup(
                jPanel_ChiTietTauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_ChiTietTauLayout.createSequentialGroup()
                                .addGroup(jPanel_ChiTietTauLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel_ChiTietTauLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel_ChiTietTauLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel6)))
                                        .addGroup(jPanel_ChiTietTauLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_ChiTietTauLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_ChiTietTauLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setBackground(new java.awt.Color(187, 205, 197));
        setPreferredSize(new java.awt.Dimension(30, 30));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_TimKiem.setBackground(new java.awt.Color(187, 205, 197));
        jPanel_TimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tìm kiếm tàu",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel_TimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_TimKiem.setPreferredSize(new java.awt.Dimension(1186, 120));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("Ga đi");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Ga đến");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Loại vé");

        buttonGroup1.add(jRadio_MotChieu);
        jRadio_MotChieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadio_MotChieu.setSelected(true);
        jRadio_MotChieu.setText("Một chiều");
        jRadio_MotChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_MotChieuActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_KhuHoi);
        jRadio_KhuHoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadio_KhuHoi.setText("Khứ hồi");
        jRadio_KhuHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_KhuHoiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setText("Ngày đi");

        txt_NgayDi.setDateFormatString("MMM d, yyyy");
        txt_NgayDi.setMaxSelectableDate(new java.util.Date(1893434475000L));
        txt_NgayDi.setMinSelectableDate(new java.util.Date(-62135791125000L));
        txt_NgayDi.setLocale(new Locale("vi", "VN"));

        txt_NgayVe.setDateFormatString("MMM d, yyyy");
        txt_NgayVe.setMaxSelectableDate(new java.util.Date(1893434475000L));
        txt_NgayVe.setMinSelectableDate(new java.util.Date(-62135791125000L));
        txt_NgayDi.setLocale(new Locale("vi", "VN"));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setText("Ngày về");

        jPanel_btnTimKiem.setBackground(new java.awt.Color(187, 205, 197));
        jPanel_btnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_btnTimKiemMouseClicked(evt);
            }
        });

        lbl_IconTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icon/buttonTimKiem.png"))); // NOI18N
        lbl_IconTimKiem.setText("jLabel1");
        lbl_IconTimKiem.setMaximumSize(new java.awt.Dimension(40, 40));
        lbl_IconTimKiem.setMinimumSize(new java.awt.Dimension(40, 40));
        lbl_IconTimKiem.setName(""); // NOI18N
        lbl_IconTimKiem.setPreferredSize(new java.awt.Dimension(40, 40));

        btn_TimKiem.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btn_TimKiem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setBorder(null);
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_btnTimKiemLayout = new javax.swing.GroupLayout(jPanel_btnTimKiem);
        jPanel_btnTimKiem.setLayout(jPanel_btnTimKiemLayout);
        jPanel_btnTimKiemLayout.setHorizontalGroup(
                jPanel_btnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                jPanel_btnTimKiemLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(lbl_IconTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()));
        jPanel_btnTimKiemLayout.setVerticalGroup(
                jPanel_btnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_btnTimKiemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_btnTimKiemLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_IconTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(9, Short.MAX_VALUE)));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setText("Loại tàu");

        buttonGroup2.add(jRadio_ChoNguoi);
        jRadio_ChoNguoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadio_ChoNguoi.setSelected(true);
        jRadio_ChoNguoi.setText("Chở người");
        jRadio_ChoNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_ChoNguoiActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadio_ChoHang);
        jRadio_ChoHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadio_ChoHang.setText("Chở hàng");
        jRadio_ChoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_ChoHangActionPerformed(evt);
            }
        });

        cbo_GaDi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        cbo_GaDen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel_TimKiemLayout = new javax.swing.GroupLayout(jPanel_TimKiem);
        jPanel_TimKiem.setLayout(jPanel_TimKiemLayout);
        jPanel_TimKiemLayout.setHorizontalGroup(
                jPanel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TimKiemLayout
                                .createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_TimKiemLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel_TimKiemLayout.createSequentialGroup()
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_TimKiemLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbo_GaDi, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_NgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_TimKiemLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_TimKiemLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbo_GaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_NgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel_TimKiemLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel_TimKiemLayout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadio_MotChieu)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadio_KhuHoi))
                                        .addGroup(jPanel_TimKiemLayout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadio_ChoNguoi)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadio_ChoHang)))
                                .addGap(31, 31, 31)
                                .addComponent(jPanel_btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(58, Short.MAX_VALUE)));
        jPanel_TimKiemLayout.setVerticalGroup(
                jPanel_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_TimKiemLayout.createSequentialGroup()
                                .addGroup(jPanel_TimKiemLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel_TimKiemLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jPanel_btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel_TimKiemLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel_TimKiemLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(jPanel_TimKiemLayout.createSequentialGroup()
                                                                .addComponent(cbo_GaDi,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(txt_NgayDi,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel_TimKiemLayout.createSequentialGroup()
                                                                .addGroup(jPanel_TimKiemLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel11,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel_TimKiemLayout
                                                                                .createSequentialGroup()
                                                                                .addGroup(jPanel_TimKiemLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(jLabel13)
                                                                                        .addComponent(jRadio_MotChieu)
                                                                                        .addComponent(jRadio_KhuHoi)
                                                                                        .addComponent(cbo_GaDen,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(4, 4, 4)))
                                                                .addGap(17, 17, 17)
                                                                .addGroup(jPanel_TimKiemLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txt_NgayVe,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel14,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addGroup(jPanel_TimKiemLayout
                                                                                .createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel16)
                                                                                .addComponent(jRadio_ChoNguoi)
                                                                                .addComponent(jRadio_ChoHang))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel_TimKiemLayout.createSequentialGroup()
                                                                        .addComponent(jLabel12)
                                                                        .addGap(26, 26, 26)
                                                                        .addComponent(jLabel15,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                30,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(9, Short.MAX_VALUE)));

        add(jPanel_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 120));
        jPanel_TimKiem.getAccessibleContext().setAccessibleName("");

        jPanel6.setBackground(new java.awt.Color(187, 205, 197));

        lbl_TimKiemVeTau1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_TimKiemVeTau1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TimKiemVeTau1.setText("TÌM KIẾM VÉ TÀU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap(503, Short.MAX_VALUE)
                                .addComponent(lbl_TimKiemVeTau1)
                                .addGap(469, 469, 469)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lbl_TimKiemVeTau1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1186, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio_ChoHangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadio_ChoHangActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jRadio_ChoHangActionPerformed

    private void jRadio_ChoNguoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadio_ChoNguoiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jRadio_ChoNguoiActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_TimKiemActionPerformed

    private void jRadio_KhuHoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadio_KhuHoiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jRadio_KhuHoiActionPerformed

    private void jRadio_MotChieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadio_MotChieuActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jRadio_MotChieuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbo_GaDen;
    private javax.swing.JComboBox<String> cbo_GaDi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_ChiTietTau;
    private javax.swing.JPanel jPanel_TimKiem;
    private javax.swing.JPanel jPanel_btnTimKiem;
    private javax.swing.JRadioButton jRadio_ChoHang;
    private javax.swing.JRadioButton jRadio_ChoNguoi;
    private javax.swing.JRadioButton jRadio_KhuHoi;
    private javax.swing.JRadioButton jRadio_MotChieu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_IconTimKiem;
    private javax.swing.JLabel lbl_TimKiemVeTau1;
    private java.awt.Panel panel1;
    private com.toedter.calendar.JDateChooser txt_NgayDi;
    private com.toedter.calendar.JDateChooser txt_NgayVe;
    // End of variables declaration//GEN-END:variables
}
