/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entity.GheEntity;
import entity.LichTrinhEntity;
import entity.VeEntity;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import util.ToanCuc;

/**
 *
 * @author ploc2
 */
public class DatVe_JFrame extends JFrame {

    private LichTrinhEntity lichTrinhHienTai;

    private ArrayList<VeEntity> gioVeHienTai = new ArrayList<>();

    private TrainSeatPanel selectedSeatPanel; // Biến để lưu ghế được chọn

    /**
     * Creates new form DatVe
     */
    public DatVe_JFrame(LichTrinhEntity lichTrinh) {

        lichTrinhHienTai = lichTrinh;

        gioVeHienTai.add(null);

        initComponents();

        jPanel_DanhSachTau.setBorder(new EmptyBorder(10, 10, 20, 10));
        jPanel_DanhSachToa.setBorder(new EmptyBorder(10, 10, 20, 10));

        // Set full màn hình
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximize cửa sổ

        for (int i = 0; i < 5; i++) {
            TrainInfoPanel panel2 = new TrainInfoPanel();
            jPanel_DanhSachTau.add(panel2);
        }

        loadToaVaoTable();
        ThongTinToaPanel toa = new ThongTinToaPanel("dau-taupng.png", 0, null);

        jPanel_DanhSachToa.add(toa);

        // load ghế ngồi vào
        loadGheVaoTable();

        // jPanel_danhSachGioVe.add(new ChiTietGioVe());
        jPanel_danhSachGioVe.add(new ChiTietGioVe());

    }

    private void loadGheVaoTable() {
        // add 40 seats to the table, top to below after left to right
        for (int i = 1; i <= 4; i++) {
            for (int j = 1; j <= 10; j++) {
                int seatNumber = (j - 1) * 4 + i;
                jPanel_DanhSachGhe.add(createSeatPanel(new GheEntity(seatNumber), seatNumber));
            }
        }
    }

    private JPanel createSeatPanel(GheEntity ghe, int seatNumber) {
        TrainSeatPanel seatPanel = new TrainSeatPanel(ghe, seatNumber);

        return seatPanel;
    }

    private void loadToaVaoTable() {
        for (int i = 0; i < 5; i++) {
            ThongTinToaPanel toa = new ThongTinToaPanel("trainCar2.png", i, null);
            jPanel_DanhSachToa.add(toa);
        }
    }

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_LamMoiActionPerformed
        lamMoi();
    }// GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_ThemVaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {
        themVaoHoaDon();
    }

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_CapNhatActionPerformed
        capNhat();
    }// GEN-LAST:event_btn_CapNhatActionPerformed

    private void btn_TaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_TaoHoaDonActionPerformed
        // TODO add your handling code here:
        taoHoaDon();
    }// GEN-LAST:event_btn_TaoHoaDonActionPerformed

    private void lamMoi() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void themVaoHoaDon() {
        GheEntity ghe = ToanCuc.getGheHienTai();
        ArrayList<GheEntity> danhSachGhe = ToanCuc.getDanhSachGheHienTai();

        danhSachGhe.add(ghe);

        ToanCuc.setDanhSachGheHienTai(danhSachGhe);

        ChiTietGioVe chiTietGioVe = new ChiTietGioVe();
        jPanel_danhSachGioVe.add(chiTietGioVe);

        jPanel_danhSachGioVe.revalidate();
        jPanel_danhSachGioVe.repaint();
        System.out.println(ghe.getMaGhe());
        return;
    }

    private void capNhat() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void taoHoaDon() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_TieuDe = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_BenTrai = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel_DanhSachTau = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel_DanhSachToa = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel_DanhSachGhe = new javax.swing.JPanel();
        btn_LamMoi = new javax.swing.JButton();
        btn_ThemVaoHoaDon = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        btn_TaoHoaDon1 = new javax.swing.JButton();
        btn_TaoHoaDon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel_GioVe = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel_danhSachGioVe = new javax.swing.JPanel();
        jPanel_ThongTinHanhTrinh = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đặt vé");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2000, 1800));

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TieuDe.setText("12321");
        jLabel_TieuDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_TieuDe.setName(""); // NOI18N

        jPanel3.setPreferredSize(new java.awt.Dimension(900, 587));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jPanel_BenTrai.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanel_BenTrai.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel_BenTrai.setRequestFocusEnabled(false);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách Tàu"));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setAlignmentX(5.0F);
        jScrollPane2.setAlignmentY(5.0F);

        jPanel_DanhSachTau.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_DanhSachTau.setAlignmentX(5.0F);
        jPanel_DanhSachTau.setAlignmentY(5.0F);
        jPanel_DanhSachTau.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_DanhSachTau.setName(""); // NOI18N
        jScrollPane2.setViewportView(jPanel_DanhSachTau);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách Toa"));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel_DanhSachToa.setBackground(new java.awt.Color(0, 204, 204));
        jScrollPane1.setViewportView(jPanel_DanhSachToa);

        jPanel_DanhSachGhe.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_DanhSachGhe.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách Ghế"));
        jPanel_DanhSachGhe.setMaximumSize(new java.awt.Dimension(800, 32767));
        jPanel_DanhSachGhe.setLayout(new java.awt.GridLayout(4, 10, 5, 5));
        jScrollPane3.setViewportView(jPanel_DanhSachGhe);

        btn_LamMoi.setBackground(new java.awt.Color(0, 51, 51));
        btn_LamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_LamMoi.setForeground(java.awt.Color.white);
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_LamMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_LamMoi.setPreferredSize(new java.awt.Dimension(90, 31));
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_ThemVaoHoaDon.setBackground(new java.awt.Color(0, 51, 51));
        btn_ThemVaoHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_ThemVaoHoaDon.setForeground(java.awt.Color.white);
        btn_ThemVaoHoaDon.setText("Thêm vào hóa đơn");
        btn_ThemVaoHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ThemVaoHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_ThemVaoHoaDon.setPreferredSize(new java.awt.Dimension(90, 31));
        btn_ThemVaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemVaoHoaDonActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(0, 51, 51));
        btn_CapNhat.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_CapNhat.setForeground(java.awt.Color.white);
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_CapNhat.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_CapNhat.setPreferredSize(new java.awt.Dimension(90, 31));
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        btn_TaoHoaDon1.setBackground(new java.awt.Color(0, 51, 51));
        btn_TaoHoaDon1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_TaoHoaDon1.setForeground(java.awt.Color.white);
        btn_TaoHoaDon1.setText("Xóa Ghế");
        btn_TaoHoaDon1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_TaoHoaDon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoHoaDon1ActionPerformed(evt);
            }
        });

        btn_TaoHoaDon.setBackground(new java.awt.Color(0, 51, 51));
        btn_TaoHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btn_TaoHoaDon.setForeground(java.awt.Color.white);
        btn_TaoHoaDon.setText("Tạo hóa đơn");
        btn_TaoHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_TaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BenTraiLayout = new javax.swing.GroupLayout(jPanel_BenTrai);
        jPanel_BenTrai.setLayout(jPanel_BenTraiLayout);
        jPanel_BenTraiLayout.setHorizontalGroup(
            jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BenTraiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BenTraiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ThemVaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TaoHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TaoHoaDon)
                .addGap(42, 42, 42))
        );
        jPanel_BenTraiLayout.setVerticalGroup(
            jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BenTraiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemVaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TaoHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(442, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel_BenTrai);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel_GioVe.setBorder(javax.swing.BorderFactory.createTitledBorder("Gio ve"));
        jPanel_GioVe.setToolTipText("");
        jPanel_GioVe.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel_GioVe.setLayout(new javax.swing.BoxLayout(jPanel_GioVe, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");

        jPanel_danhSachGioVe.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane4.setViewportView(jPanel_danhSachGioVe);

        jPanel_GioVe.add(jScrollPane4);

        jPanel2.add(jPanel_GioVe, java.awt.BorderLayout.PAGE_START);

        jPanel_ThongTinHanhTrinh.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_ThongTinHanhTrinh.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hành trình"));

        javax.swing.GroupLayout jPanel_ThongTinHanhTrinhLayout = new javax.swing.GroupLayout(jPanel_ThongTinHanhTrinh);
        jPanel_ThongTinHanhTrinh.setLayout(jPanel_ThongTinHanhTrinhLayout);
        jPanel_ThongTinHanhTrinhLayout.setHorizontalGroup(
            jPanel_ThongTinHanhTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel_ThongTinHanhTrinhLayout.setVerticalGroup(
            jPanel_ThongTinHanhTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel_ThongTinHanhTrinh, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_TieuDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1612, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TaoHoaDon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoHoaDon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TaoHoaDon1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_TaoHoaDon;
    private javax.swing.JButton btn_TaoHoaDon1;
    private javax.swing.JButton btn_ThemVaoHoaDon;
    private javax.swing.JLabel jLabel_TieuDe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_BenTrai;
    private javax.swing.JPanel jPanel_DanhSachGhe;
    private javax.swing.JPanel jPanel_DanhSachTau;
    private javax.swing.JPanel jPanel_DanhSachToa;
    private javax.swing.JPanel jPanel_GioVe;
    private javax.swing.JPanel jPanel_ThongTinHanhTrinh;
    private javax.swing.JPanel jPanel_danhSachGioVe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

}
