/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entity.KhachHangEntity;
import entity.VeEntity;
import util.ToanCuc;

/**
 *
 * @author ploc2
 */
public class GanHanhKhachVaoVe_GUI extends javax.swing.JFrame {

        /**
         * Creates new form GanHanhKhachVaoVe_GUI
         */
        private VeEntity ve;

        public GanHanhKhachVaoVe_GUI(VeEntity ve) {
                initComponents();

                this.ve = ve;

                btn_Gan.addActionListener(e -> ganThongTin());
        }

        private void ganThongTin() {
                // Kiểm tra xem các ô nhập liệu có rỗng không
                if (txt_hoTen.getText().isEmpty() || txt_CMND.getText().isEmpty() || txt_tuoi.getText().isEmpty()) {
                        // Nếu có ô nào rỗng, có thể hiển thị thông báo
                        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Cảnh báo",
                                        javax.swing.JOptionPane.WARNING_MESSAGE);
                } else {
                        // Nếu không rỗng, cập nhật tiêu đề
                        jLabel_TieuDe.setText("Vé" + this.ve.getGia() + " - " + this.ve.getGhe().getMaGhe());

                        // Lấy thông tin từ các ô nhập liệu (nếu cần)
                        String hoTen = txt_hoTen.getText();
                        String cmnd = txt_CMND.getText();
                        String tuoi = txt_tuoi.getText();

                        KhachHangEntity khachHang = new KhachHangEntity();

                        khachHang.setHoTen(hoTen);
                        khachHang.setTuoi(Integer.parseInt(tuoi));
                        khachHang.setSoCCCD(cmnd);

                        VeEntity ve = new VeEntity();

                        ve.setKhachHang(khachHang);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel_TieuDe = new javax.swing.JLabel();
                txt_hoTen = new javax.swing.JTextField();
                txt_CMND = new javax.swing.JTextField();
                CMND = new javax.swing.JLabel();
                txt_tuoi = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                btn_Gan = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setText("Họ và tên");

                jLabel_TieuDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel_TieuDe.setText("TieuDe");

                CMND.setText("Số căn cước");

                jLabel4.setText("Tuổi");

                btn_Gan.setBackground(new java.awt.Color(0, 255, 51));
                btn_Gan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btn_Gan.setText("Gán");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(43, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(CMND,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                79,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txt_CMND,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                217,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                79,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txt_hoTen,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                217,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                79,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(txt_tuoi,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                217,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(33, 33, 33))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(147, 147, 147)
                                                                .addComponent(btn_Gan)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel_TieuDe,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txt_hoTen,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(CMND,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txt_CMND,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txt_tuoi,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                27,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btn_Gan)
                                                                .addContainerGap(8, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel CMND;
        private javax.swing.JButton btn_Gan;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel_TieuDe;
        private javax.swing.JTextField txt_CMND;
        private javax.swing.JTextField txt_hoTen;
        private javax.swing.JTextField txt_tuoi;
        // End of variables declaration//GEN-END:variables
}
