	/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import bus.NhanVien_bus;
import entity.GioiTinhEnum;
import entity.NhanVienEntity;
import java.awt.Image;
import java.net.URL;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import util.GenerateID;

/**
 *
 * @author 84335
 */
public class NhanVien_JPanel extends javax.swing.JPanel {
	private DefaultTableModel tableModel = new DefaultTableModel();
	private NhanVien_bus bus = new NhanVien_bus();

	/**
	 * Creates new form NhanVien_JPanel
	 */
	public NhanVien_JPanel() {
		initComponents();
		setBounds(0, 0, 1186, 748);

		URL imageTimKiem = NhanVien_JPanel.class.getResource("/pic/icon/buttonTimKiem.png");
		ImageIcon img_btnTimKiem = new ImageIcon(imageTimKiem);
		Image scaled_btnTimKiem = img_btnTimKiem.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
		img_btnTimKiem = new ImageIcon(scaled_btnTimKiem);
		btn_TimKiem.setIcon(img_btnTimKiem);

		URL imageThem = NhanVien_JPanel.class.getResource("/pic/icon/buttonThem.png");
		ImageIcon img_btnThem = new ImageIcon(imageThem);
		Image scaled_btnThem = img_btnThem.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
		img_btnThem = new ImageIcon(scaled_btnThem);
		btn_Them.setIcon(img_btnThem);

		URL imageLamMoi = NhanVien_JPanel.class.getResource("/pic/icon/buttonLamMoi.png");
		ImageIcon img_btnLamMoi = new ImageIcon(imageLamMoi);
		Image scaled_btnLamMoi = img_btnLamMoi.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
		img_btnLamMoi = new ImageIcon(scaled_btnLamMoi);
		btn_LamMoi.setIcon(img_btnLamMoi);

		URL imageCapNhat = NhanVien_JPanel.class.getResource("/pic/icon/buttonCapNhat.png");
		ImageIcon img_btnCapNhat = new ImageIcon(imageCapNhat);
		Image scaled_btnCapNhat = img_btnCapNhat.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
		img_btnCapNhat = new ImageIcon(scaled_btnCapNhat);
		btn_CapNhat.setIcon(img_btnCapNhat);

		tableModel = (DefaultTableModel) table_DanhSachNV.getModel();
		table_DanhSachNV.setModel(tableModel);

		loadData();

		refresh();

		table_DanhSachNV.setDefaultEditor(Object.class, null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		panel_QuanLyNV = new javax.swing.JPanel();
		lbl_QuanLyNV = new javax.swing.JLabel();
		panel_ThongTinNV = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		lbl_NgaySinhNV = new javax.swing.JLabel();
		lbl_EmailNV = new javax.swing.JLabel();
		txt_HoTenNV = new javax.swing.JLabel();
		lbl_GioiTinhNV = new javax.swing.JLabel();
		lbl_ChucVuNV = new javax.swing.JLabel();
		lbl_SDTNhanVien = new javax.swing.JLabel();
		lbl_DiaChiNV = new javax.swing.JLabel();
		lbl_TinhTrangNV = new javax.swing.JLabel();
		txt_email = new javax.swing.JTextField();
		txt_HoTen = new javax.swing.JTextField();
		txt_SDT = new javax.swing.JTextField();
		txt_MaNV = new javax.swing.JTextField();
		txt_DiaChi = new javax.swing.JTextField();
		rad_Nam = new javax.swing.JRadioButton();
		rad_Nu = new javax.swing.JRadioButton();
		rad_Khac = new javax.swing.JRadioButton();
		cbo_ChucVu = new javax.swing.JComboBox<>();
		cbo_TinhTrang = new javax.swing.JComboBox<>();
		txt_date = new com.toedter.calendar.JDateChooser();
		panel_ThaoTaoNV = new javax.swing.JPanel();
		lbl_NhapSDT = new javax.swing.JLabel();
		txt_NhapSDT = new javax.swing.JTextField();
		btn_TimKiem = new javax.swing.JButton();
		btn_LamMoi = new javax.swing.JButton();
		btn_Them = new javax.swing.JButton();
		btn_CapNhat = new javax.swing.JButton();
		panel_TableNhanVien = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		table_DanhSachNV = new javax.swing.JTable();

		setBackground(new java.awt.Color(187, 205, 197));
		setPreferredSize(new java.awt.Dimension(1020, 700));
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		panel_QuanLyNV.setBackground(new java.awt.Color(187, 205, 197));

		lbl_QuanLyNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		lbl_QuanLyNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbl_QuanLyNV.setText("QUẢN LÝ NHÂN VIÊN");
		panel_QuanLyNV.add(lbl_QuanLyNV);

		add(panel_QuanLyNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1186, -1));

		panel_ThongTinNV.setBackground(new java.awt.Color(187, 205, 197));
		panel_ThongTinNV.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin nhân viên",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

		jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		jLabel1.setText("Mã nhân viên");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

	    lbl_NgaySinhNV.setFont(new java.awt.Font("Times New Roman", 0, 16));
		lbl_NgaySinhNV.setText("Ngày tạo");

		lbl_EmailNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		lbl_EmailNV.setText("Email");

		txt_HoTenNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		txt_HoTenNV.setText("Họ tên");

		lbl_GioiTinhNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		lbl_GioiTinhNV.setText("Giới tính");

		lbl_ChucVuNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		lbl_ChucVuNV.setText("Chức vụ");

		lbl_SDTNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		lbl_SDTNhanVien.setText("Số điện thoại");

		lbl_DiaChiNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		lbl_DiaChiNV.setText("Địa chỉ");

		lbl_TinhTrangNV.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		lbl_TinhTrangNV.setText("Tình trạng");

		txt_email.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		txt_email.setPreferredSize(new java.awt.Dimension(200, 30));
		txt_email.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txt_emailActionPerformed(evt);
			}
		});

		txt_HoTen.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		txt_HoTen.setPreferredSize(new java.awt.Dimension(200, 30));
		txt_HoTen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txt_HoTenActionPerformed(evt);
			}
		});

		txt_SDT.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		txt_SDT.setPreferredSize(new java.awt.Dimension(200, 30));
		txt_SDT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txt_SDTActionPerformed(evt);
			}
		});

		txt_MaNV.setEditable(false);
		txt_MaNV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		txt_MaNV.setFocusable(false);
		txt_MaNV.setPreferredSize(new java.awt.Dimension(200, 30));
		txt_MaNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txt_MaNVActionPerformed(evt);
			}
		});

		txt_DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		txt_DiaChi.setPreferredSize(new java.awt.Dimension(200, 30));
		txt_DiaChi.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txt_DiaChiActionPerformed(evt);
			}
		});

		rad_Nam.setBackground(new java.awt.Color(187, 205, 197));
		buttonGroup1.add(rad_Nam);
		rad_Nam.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		rad_Nam.setText("Nam");
		rad_Nam.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//                rad_NamActionPerformed(evt);
			}
		});

		rad_Nu.setBackground(new java.awt.Color(187, 205, 197));
		buttonGroup1.add(rad_Nu);
		rad_Nu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		rad_Nu.setText("Nữ");

		rad_Khac.setBackground(new java.awt.Color(187, 205, 197));
		buttonGroup1.add(rad_Khac);
		rad_Khac.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		rad_Khac.setText("Khác");
		rad_Khac.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//                rad_KhacActionPerformed(evt);
			}
		});

		cbo_ChucVu.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		cbo_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý" }));
		cbo_ChucVu.setPreferredSize(new java.awt.Dimension(200, 30));
		cbo_ChucVu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbo_ChucVuActionPerformed(evt);
			}
		});

		cbo_TinhTrang.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		cbo_TinhTrang.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "Nghỉ phép", "Nghỉ việc" }));
		cbo_TinhTrang.setPreferredSize(new java.awt.Dimension(200, 30));
		cbo_TinhTrang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//                cbo_TinhTrangActionPerformed(evt);
			}
		});

		txt_date.setDateFormatString("MMM d, yyyy");
		txt_date.setLocale(new Locale("vi", "VN"));

		javax.swing.GroupLayout panel_ThongTinNVLayout = new javax.swing.GroupLayout(panel_ThongTinNV);
		panel_ThongTinNV.setLayout(panel_ThongTinNVLayout);
		panel_ThongTinNVLayout.setHorizontalGroup(panel_ThongTinNVLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_ThongTinNVLayout.createSequentialGroup().addGap(40, 40, 40)
						.addGroup(panel_ThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panel_ThongTinNVLayout.createSequentialGroup().addGroup(panel_ThongTinNVLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(panel_ThongTinNVLayout.createSequentialGroup()
												.addComponent(lbl_GioiTinhNV).addGap(46, 46, 46).addComponent(rad_Nam)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(rad_Nu).addGap(18, 18, 18).addComponent(rad_Khac))
										.addGroup(panel_ThongTinNVLayout.createSequentialGroup()
												.addComponent(txt_HoTenNV).addGap(58, 58, 58).addComponent(txt_HoTen,
														javax.swing.GroupLayout.PREFERRED_SIZE, 190,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(43, 43, 43)
										.addGroup(panel_ThongTinNVLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(panel_ThongTinNVLayout.createSequentialGroup()
														.addComponent(lbl_ChucVuNV).addGap(18, 18, 18)
														.addComponent(cbo_ChucVu, 0, 1, Short.MAX_VALUE)
														.addGap(18, 18, 18).addComponent(lbl_TinhTrangNV))
												.addGroup(panel_ThongTinNVLayout.createSequentialGroup()
														.addComponent(lbl_EmailNV).addGap(30, 30, 30)
														.addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE,
																190, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(panel_ThongTinNVLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(panel_ThongTinNVLayout.createSequentialGroup()
														.addGap(27, 27, 27).addComponent(lbl_DiaChiNV)
														.addGap(463, 463, 463))
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														panel_ThongTinNVLayout.createSequentialGroup().addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(cbo_TinhTrang,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 124,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addContainerGap(410, Short.MAX_VALUE))))
								.addGroup(panel_ThongTinNVLayout.createSequentialGroup().addComponent(jLabel1)
										.addGap(18, 18, 18)
										.addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28).addComponent(lbl_NgaySinhNV).addGap(18, 18, 18)
										.addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(24, 24, 24).addComponent(lbl_SDTNhanVien).addGap(18, 18, 18)
										.addGroup(panel_ThongTinNVLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()))));
		panel_ThongTinNVLayout.setVerticalGroup(panel_ThongTinNVLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_ThongTinNVLayout.createSequentialGroup().addGap(7, 7, 7).addGroup(panel_ThongTinNVLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panel_ThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addGroup(panel_ThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_NgaySinhNV).addComponent(lbl_SDTNhanVien).addComponent(txt_SDT,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(panel_ThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(panel_ThongTinNVLayout.createSequentialGroup().addGap(12, 12, 12)
										.addGroup(panel_ThongTinNVLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txt_HoTenNV)
												.addGroup(panel_ThongTinNVLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(lbl_DiaChiNV).addComponent(lbl_EmailNV)
														.addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGroup(panel_ThongTinNVLayout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(12, 12, 12)
						.addGroup(panel_ThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_GioiTinhNV).addComponent(rad_Nam).addComponent(rad_Nu)
								.addComponent(rad_Khac).addComponent(lbl_ChucVuNV)
								.addComponent(cbo_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_TinhTrangNV).addComponent(cbo_TinhTrang,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(44, 44, 44)));

		add(panel_ThongTinNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 1175, 160));

		panel_ThaoTaoNV.setBackground(new java.awt.Color(187, 205, 197));
		panel_ThaoTaoNV.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Các thao tác",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

		lbl_NhapSDT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		lbl_NhapSDT.setText("Nhập số điện thoại");

		txt_NhapSDT.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
		txt_NhapSDT.setPreferredSize(new java.awt.Dimension(200, 30));
		txt_NhapSDT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txt_NhapSDTActionPerformed(evt);
			}
		});

		btn_TimKiem.setBackground(new java.awt.Color(0, 51, 51));
		btn_TimKiem.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
		btn_TimKiem.setText("Tìm kiếm");
		btn_TimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btn_TimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_TimKiemMouseClicked(evt);
			}
		});
		btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btn_TimKiemActionPerformed(evt);
			}
		});

		btn_LamMoi.setBackground(new java.awt.Color(0, 51, 51));
		btn_LamMoi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		btn_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
		btn_LamMoi.setText("Làm mới");
		btn_LamMoi.setToolTipText("");
		btn_LamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btn_LamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
		    public void mouseClicked(java.awt.event.MouseEvent evt) {
		        btn_LamMoiMouseClicked(evt);
		    }
		});

		btn_Them.setBackground(new java.awt.Color(0, 51, 51));
		btn_Them.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		btn_Them.setForeground(new java.awt.Color(255, 255, 255));
		btn_Them.setText("Thêm");
		btn_Them.setToolTipText("");
		btn_Them.setActionCommand("");
		btn_Them.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btn_Them.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_ThemActionPerformed(evt);
			}
		});

		btn_CapNhat.setBackground(new java.awt.Color(0, 51, 51));
		btn_CapNhat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
		btn_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
		btn_CapNhat.setText("Cập nhật");
		btn_CapNhat.setToolTipText("");
		btn_CapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_CapNhatActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panel_ThaoTaoNVLayout = new javax.swing.GroupLayout(panel_ThaoTaoNV);
		panel_ThaoTaoNV.setLayout(panel_ThaoTaoNVLayout);
		panel_ThaoTaoNVLayout
				.setHorizontalGroup(panel_ThaoTaoNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panel_ThaoTaoNVLayout.createSequentialGroup().addGap(6, 6, 6)
								.addComponent(lbl_NhapSDT).addGap(18, 18, 18)
								.addComponent(txt_NhapSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 292,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		panel_ThaoTaoNVLayout.setVerticalGroup(panel_ThaoTaoNVLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panel_ThaoTaoNVLayout.createSequentialGroup().addGap(13, 13, 13)
						.addGroup(panel_ThaoTaoNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lbl_NhapSDT)
								.addComponent(txt_NhapSDT, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(17, 17, 17)));

		add(panel_ThaoTaoNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 230, 1175, 80));

		panel_TableNhanVien.setBackground(new java.awt.Color(187, 205, 197));
		panel_TableNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bảng danh sách nhân viên",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
		panel_TableNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		table_DanhSachNV.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã", "Họ tên", "Giới tính", "Loại", "Email", "Số điện thoại", "Địa chỉ", "Trạng thái",
				"Ngày Tạo", "Ngày Cập Nhật" }));
		table_DanhSachNV.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				table_DanhSachNVMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(table_DanhSachNV);

		panel_TableNhanVien.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1150, 400));

		add(panel_TableNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1170, 430));
	}// </editor-fold>//GEN-END:initComponents

	private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_emailActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_emailActionPerformed

	private void txt_HoTenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_HoTenActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_HoTenActionPerformed

	private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_SDTActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_SDTActionPerformed

	private void txt_MaNVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_MaNVActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_MaNVActionPerformed

	private void txt_DiaChiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_DiaChiActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_DiaChiActionPerformed

	private void cbo_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbo_ChucVuActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cbo_ChucVuActionPerformed

	private void txt_NhapSDTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_NhapSDTActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txt_NhapSDTActionPerformed

	private void btn_LamMoiMouseClicked(java.awt.event.MouseEvent evt) {
	    refresh();
	}
	private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {
	    try {
	        if (checkInput()) {
	            NhanVienEntity nv = new NhanVienEntity();
	            nv.setMaNV(GenerateID.sinhMa("NV"));
	            nv.setTen(txt_HoTen.getText());
	            
	            nv.setGioiTinh(rad_Nam.isSelected() ? GioiTinhEnum.NAM : 
	                          rad_Nu.isSelected() ? GioiTinhEnum.NU : 
	                          GioiTinhEnum.KHAC);

	            nv.setEmail(txt_email.getText());
	            nv.setSoDienThoai(txt_SDT.getText());
	            nv.setDiaChi(txt_DiaChi.getText());
	            nv.setLoai(cbo_ChucVu.getSelectedIndex());
	            nv.setTrangThai(TinhTrangNVEnum.values()[cbo_TinhTrang.getSelectedIndex()]);
	            
	            // Lấy ngày tạo từ date chooser
	            nv.setNgayTao(txt_date.getDate());
	            nv.setNgayCapNhat(new Date());
	            
	            if (bus.insert(nv)) {
	                refresh();
	                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
	            } else {
	                JOptionPane.showMessageDialog(this, "Thêm thất bại! Số điện thoại nhân viên đã bị trùng!");
	            }
	        }
	    } catch (BadLocationException ex) {
	        Logger.getLogger(NhanVien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}

	private void table_DanhSachNVMouseClicked(java.awt.event.MouseEvent evt) {
	    try {
	        int rowSelected = table_DanhSachNV.getSelectedRow();
	        if (rowSelected == -1) return;
	        txt_MaNV.setText(tableModel.getValueAt(rowSelected, 0).toString());
	        txt_HoTen.setText(tableModel.getValueAt(rowSelected, 1).toString());
	        String gender = tableModel.getValueAt(rowSelected, 2).toString();
	        switch (gender) {
	            case "Nam" -> rad_Nam.setSelected(true);
	            case "Nữ" -> rad_Nu.setSelected(true);
	            case "Khác" -> rad_Khac.setSelected(true);
	        }
	        String loai = tableModel.getValueAt(rowSelected, 3).toString();
	        cbo_ChucVu.setSelectedIndex(loai.equals("Quản lý") ? 1 : 0);
	        txt_email.setText(tableModel.getValueAt(rowSelected, 4).toString());
	        txt_SDT.setText(tableModel.getValueAt(rowSelected, 5).toString());
	        txt_DiaChi.setText(tableModel.getValueAt(rowSelected, 6).toString());
	        String trangThai = tableModel.getValueAt(rowSelected, 7).toString();
	        for (int i = 0; i < cbo_TinhTrang.getItemCount(); i++) {
	            if (cbo_TinhTrang.getItemAt(i).toString().equals(trangThai)) {
	                cbo_TinhTrang.setSelectedIndex(i);
	                break;
	            }
	        }
	        
	        if (tableModel.getValueAt(rowSelected, 8) != null) {
	            txt_date.setDate((Date) tableModel.getValueAt(rowSelected, 8));
	        }
	        btn_Them.setEnabled(false);
	        
	    } catch (Exception ex) {
	        Logger.getLogger(NhanVien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
	        JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị thông tin: " + ex.getMessage());
	    }
	}

	private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {
	    try {
	        if (table_DanhSachNV.getSelectedRow() == -1) {
	            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần cập nhật!");
	            return;
	        }

	        if (!checkInput()) {
	            return;
	        }

	        NhanVienEntity nv = new NhanVienEntity();
	        nv.setMaNV(txt_MaNV.getText());
	        nv.setTen(txt_HoTen.getText());
	        
	        // Set giới tính
	        nv.setGioiTinh(rad_Nam.isSelected() ? GioiTinhEnum.NAM : 
	                       rad_Nu.isSelected() ? GioiTinhEnum.NU : 
	                       GioiTinhEnum.KHAC);
	        
//	        // Set ngày sinh
//	        if (txt_date.getDate() != null) {
//	            nv.setNgaySinh(txt_date.getDate());
//	        }
	        
	        nv.setEmail(txt_email.getText());
	        nv.setSoDienThoai(txt_SDT.getText());
	        nv.setDiaChi(txt_DiaChi.getText());
	        nv.setLoai(cbo_ChucVu.getSelectedIndex());
	        nv.setTrangThai(TinhTrangNVEnum.values()[cbo_TinhTrang.getSelectedIndex()]);
	        
	        // Set ngày cập nhật
	        Date currentDate = Date.from(LocalDate.now().atStartOfDay(ZoneId.systemDefault()).toInstant());
	        nv.setNgayCapNhat(currentDate);

	        if (bus.update(nv)) {
	            refresh();
	            JOptionPane.showMessageDialog(this, "Cập nhật thông tin nhân viên thành công!");
	        } else {
	            JOptionPane.showMessageDialog(this, "Cập nhật thất bại! Vui lòng kiểm tra lại thông tin.");
	        }
	        
	    } catch (BadLocationException ex) {
	        Logger.getLogger(NhanVien_JPanel.class.getName()).log(Level.SEVERE, null, ex);
	        JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
	    } catch (Exception e) {
	        Logger.getLogger(NhanVien_JPanel.class.getName()).log(Level.SEVERE, null, e);
	        JOptionPane.showMessageDialog(this, "Lỗi không xác định: " + e.getMessage());
	    }
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_CapNhat;
	private javax.swing.JButton btn_LamMoi;
	private javax.swing.JButton btn_Them;
	private javax.swing.JButton btn_TimKiem;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JComboBox<String> cbo_ChucVu;
	private javax.swing.JComboBox<String> cbo_TinhTrang;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lbl_ChucVuNV;
	private javax.swing.JLabel lbl_DiaChiNV;
	private javax.swing.JLabel lbl_EmailNV;
	private javax.swing.JLabel lbl_GioiTinhNV;
	private javax.swing.JLabel lbl_NgaySinhNV;
	private javax.swing.JLabel lbl_NhapSDT;
	private javax.swing.JLabel lbl_QuanLyNV;
	private javax.swing.JLabel lbl_SDTNhanVien;
	private javax.swing.JLabel lbl_TinhTrangNV;
	private javax.swing.JPanel panel_QuanLyNV;
	private javax.swing.JPanel panel_TableNhanVien;
	private javax.swing.JPanel panel_ThaoTaoNV;
	private javax.swing.JPanel panel_ThongTinNV;
	private javax.swing.JRadioButton rad_Khac;
	private javax.swing.JRadioButton rad_Nam;
	private javax.swing.JRadioButton rad_Nu;
	private javax.swing.JTable table_DanhSachNV;
	private javax.swing.JTextField txt_DiaChi;
	private javax.swing.JTextField txt_HoTen;
	private javax.swing.JLabel txt_HoTenNV;
	private javax.swing.JTextField txt_MaNV;
	private javax.swing.JTextField txt_NhapSDT;
	private javax.swing.JTextField txt_SDT;
	private com.toedter.calendar.JDateChooser txt_date;
	private javax.swing.JTextField txt_email;
	// End of variables declaration//GEN-END:variables

	// Sửa lại phương thức loadData()
	private void loadData() {
	    try {
	        ArrayList<NhanVienEntity> listNV = bus.findAll();
	        tableModel.setRowCount(0);
	        
	        // Debug
	        System.out.println("Loading data to table...");
	        
	        for (NhanVienEntity nv : listNV) {
	            String gioiTinh = nv.getGioiTinh() != null ? nv.getGioiTinh().toString() : "N/A";
	            String loai = nv.getLoai() == 1 ? "Quản lý" : "Nhân viên";
	            String trangThai = nv.getTrangThai() != null ? nv.getTrangThai().toString() : "N/A";
	            
	            Object[] row = {
	                nv.getMaNV(),
	                nv.getTen(),
	                gioiTinh,
	                loai,
	                nv.getEmail(),
	                nv.getSoDienThoai(),
	                nv.getDiaChi(),
	                trangThai,
	                nv.getNgayTao(),
	                nv.getNgayCapNhat()
	            };
	            
	            tableModel.addRow(row);
	            
	            // Debug
	            System.out.println("Added employee: " + nv.getMaNV() + " - " + nv.getTen());

	        }
									table_DanhSachNV.setModel(tableModel);
	    } catch (Exception e) {
	        e.printStackTrace();
	        JOptionPane.showMessageDialog(null, "Lỗi khi tải dữ liệu: " + e.getMessage());
	    }
	}

	public boolean checkInput() throws BadLocationException {
	    String hoTen = txt_HoTen.getText();
	    String SDT = txt_SDT.getText();
	    String diaChi = txt_DiaChi.getText();
	    String email = txt_email.getText();
	    Date ngayTao = txt_date.getDate();

	    if (hoTen.isBlank() || SDT.isBlank() || diaChi.isBlank() || ngayTao == null
	            || (rad_Nam.isSelected() == false && rad_Nu.isSelected() == false && rad_Khac.isSelected() == false)) {
	        JOptionPane.showMessageDialog(this, "Tất cả thông tin không được rỗng!");
	        return false;
	    } else if (!hoTen.matches(
				"^[A-ZÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ][a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]*(?:[ ][A-ZÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ][a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]*)*$")) {
			JOptionPane.showMessageDialog(this,
					"Họ tên phải viết hoa chữ cái đầu và phải có khoảng trắng giữa các cụm!");
			txt_HoTen.requestFocus();
			txt_HoTen.selectAll();
			return false;
		} else if (!SDT.matches("^(0|84)[1-9]\\d{8}$")) {
			JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 ký số và thuộc quốc gia Việt Nam!");
			txt_NhapSDT.requestFocus();
			txt_NhapSDT.selectAll();
			return false;
		} else if (!diaChi.matches(
				"^([A-ZÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ][a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]*(?:[ ][A-ZÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ][a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ,]*))*|([a-zA-Z0-9.]+)+$")
				&& diaChi.length() > 50) {
			JOptionPane.showMessageDialog(this, "Địa chỉ không hợp lệ!");
			return false;
//		} else if (NhanVienEntity.getAge(LocalDate.now(),
//				birthDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()) < 15) {
//			JOptionPane.showMessageDialog(this, "Nhân viên phải đủ 15 tuổi trở lên mới được nhận!");
//			return false;
		} else if (!email.matches("^[a-z][a-z0-9_\\.]{5,32}@[a-z0-9]{2,}(\\.[a-z0-9]{2,4}){1,2}$")) {
			JOptionPane.showMessageDialog(this, "Địa chỉ email không hợp lệ!");
			return false;
		}
		return true;
	}

	public void refresh() {
	    txt_MaNV.setText("");
	    txt_HoTen.setText("");
	    txt_DiaChi.setText("");
	    txt_SDT.setText("");
	    txt_NhapSDT.setText("");
	    buttonGroup1.clearSelection();
	    tableModel.setRowCount(0);
	    cbo_ChucVu.setSelectedIndex(0);
	    cbo_TinhTrang.setSelectedIndex(0);
	    txt_email.setText("");
	    rad_Nam.setSelected(true);
	    
	    // Set ngày tạo là ngày hiện tại và enable date chooser cho nhân viên mới
	    txt_date.setDate(new Date());
	    txt_date.setEnabled(true);
	    
	    btn_Them.setEnabled(true);
	    loadData();
	}
}
