/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author ploc2
 */
public class NhaSanXuat_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form NhaSanXuat
     */
    public NhaSanXuat_JPanel() {
        initComponents();
                setVisible(true);
        setBounds(0, 0, 1186, 748);
        
        URL image_TrangChu = TrangChu_JPanel.class.getResource("/pic/icon/thanh-vien-nhom.png");
        ImageIcon img_TrangChu = new ImageIcon(image_TrangChu);
        Image scaled_TrangChu = img_TrangChu.getImage().getScaledInstance(1186, 748, Image.SCALE_SMOOTH);
        img_TrangChu = new ImageIcon(scaled_TrangChu);
        lbl_IConTrangChu.setIcon(img_TrangChu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_IConTrangChu = new javax.swing.JLabel();

        lbl_IConTrangChu.setPreferredSize(new java.awt.Dimension(1355, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_IConTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl_IConTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_IConTrangChu;
    // End of variables declaration//GEN-END:variables
}
