/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.BorderFactory;
import javax.swing.JPanel;

import entity.GheEntity;
import util.ToanCuc;

/**
 *
 * @author ploc2
 */
public class TrainSeatPanel extends JPanel {
    /**
     * Creates new form TrainSeatPanel
     */
    private int soGhe = 0;
    private GheEntity ghe;
    private Color mauDangChon = new Color(153, 255, 51);
    private Color mauMacDinh = new Color(244, 244, 244);
    private Color mauGheDaDat = new Color(255, 153, 153);
    // private Color mauGheDaDat = new Color(255, 153, 153);

    public TrainSeatPanel(GheEntity ghe, int soGhe) {
        this.soGhe = soGhe;
        this.ghe = ghe;
        initComponents();

        // // Tạo hiệu ứng hover (optional)
        // addMouseListener(new MouseAdapter() {
        // @Override
        // public void mouseEntered(MouseEvent e) {
        // batMauNut();
        // }
        //
        // @Override
        // public void mouseExited(MouseEvent e) {
        // resetMauNut();
        // }
        // });

        // // Tạo hiệu ứng hover (optional)
        // jLabel_Ghe.addMouseListener(new MouseAdapter() {
        // @Override
        // public void mouseEntered(MouseEvent e) {
        // batMauNut();
        // }
        //
        // @Override
        // public void mouseExited(MouseEvent e) {
        // resetMauNut();
        //
        // }
        // });
        jLabel_Ghe.setText(soGhe + "");

        jLabel_Ghe.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Nếu ghế hiện tại đang được chọn
                if (ToanCuc.getGheHienTai() != null && ToanCuc.getGheHienTai().equals(ghe)) {
                    // Bỏ chọn ghế, đổi màu thành xám
                    setBackground(Color.lightGray);
                    System.out.println("Bỏ chọn ghế: " + (ghe == null ? "null" : ghe.toString()));
                    ToanCuc.setGheHienTai(null); // Cập nhật ghế hiện tại thành null
                    ToanCuc.setjLabelGheHienTai(null); // Đặt jLabel hiện tại thành null
                } else {
                    // Nếu có ghế đang được chọn, đổi màu chúng về xám
                    if (ToanCuc.getjLabelGheHienTai() != null) {
                        ToanCuc.getjLabelGheHienTai().setBackground(Color.lightGray);
                    }

                    // Đánh dấu ghế hiện tại là đã chọn
                    setBackground(Color.GREEN);
                    ToanCuc.setGheHienTai(ghe); // Lưu thông tin ghế hiện tại
                    ToanCuc.setjLabelGheHienTai(jLabel_Ghe); // Cập nhật jLabel hiện tại

                    System.out.println("Ghế được chọn: " + (ghe == null ? "null" : ghe.toString()));
                }
            }
        });

    }

    private void resetMauNut() {
        setBackground(mauMacDinh);
        jLabel_Ghe.setBackground(new Color(244, 244, 244));
    }

    private void batMauNut() {

        setBackground(mauDangChon);
        jLabel_Ghe.setBackground(mauDangChon);
    }

    public int getSoGhe() {
        return soGhe;
    }

    public GheEntity getGhe() {
        return ghe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Ghe = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(40, 40));
        setMinimumSize(new java.awt.Dimension(40, 40));
        setPreferredSize(new java.awt.Dimension(40, 40));

        jPanel1.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel_Ghe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Ghe.setText("jLabel1");
        jLabel_Ghe.setAlignmentY(0.0F);
        jLabel_Ghe.setIconTextGap(0);
        jLabel_Ghe.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel_Ghe.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabel_Ghe.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Ghe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Ghe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Ghe;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
