/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import entity.LichTrinhEntity;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import entity.TauEntity;
import util.ToanCuc;

/**
 *
 * @author ploc2
 */
public class TrainInfoPanel extends javax.swing.JPanel {

        private JLabel trainNumberLabel;
        private JLabel departureTimeLabel;
        private JLabel arrivalTimeLabel;
        private JLabel availableSeatsLabel;

        private DatVe_JFrame datVe_JFrame;

        private TauEntity tauHienTai;
        private LichTrinhEntity lichTrinhHienTai;

        public TrainInfoPanel(TauEntity tau, LichTrinhEntity lt, DatVe_JFrame datVe_JFrame) {
                initComponents();
                this.datVe_JFrame = datVe_JFrame;
                this.tauHienTai = tau;
                this.lichTrinhHienTai = lt;

                jLabel_SoLuongDaDat.setText(tau.getSoLuongDaDat() + "");
                jLabel_SoLuongGheTrong.setText(tau.getSoLuongGheTrong() + "");
                jLabel_ThoiGianDi.setText(lichTrinhHienTai.getNgayDi() + "   " + lichTrinhHienTai.getGioDi());
                jLabel_ThoiGianDen.setText(lichTrinhHienTai.getNgayDen() + "   " + lichTrinhHienTai.getGioDen());
                jLabel_tenTau.setText(tau.getTenTau() + " - " + tau.getMaTau());

                // Tạo hiệu ứng hover (optional)
                addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                                // if background is blue, change it to white

                                if (getBackground().equals(new Color(0, 120, 190))) {
                                        setBackground(Color.WHITE);
                                } else {
                                        setBackground(new Color(0, 120, 190));
                                        datVe_JFrame.loadToaVaoTable(tau.getMaTau());
                                        ToanCuc.setTauHienTai(tau);
                                        ToanCuc.setLichTrinh(lichTrinhHienTai);
                                }
                        }
                });

        }

        // Các methods để cập nhật thông tin
        public void setTrainInfo(String trainNumber, String departureTime,
                        String arrivalTime, int availableSeats) {
                trainNumberLabel.setText(trainNumber);
                departureTimeLabel.setText("TG đi: " + departureTime);
                arrivalTimeLabel.setText("TG đến: " + arrivalTime);
                availableSeatsLabel.setText("SL chỗ trống: " + availableSeats);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel_tenTau = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel_ThoiGianDi = new javax.swing.JLabel();
                jLabel_ThoiGianDen = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel_SoLuongGheTrong = new javax.swing.JLabel();
                jLabel_SoLuongDaDat = new javax.swing.JLabel();

                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                formMouseClicked(evt);
                        }
                });

                jLabel_tenTau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel_tenTau.setText("Tàu 8");
                jLabel_tenTau.setToolTipText("");
                jLabel_tenTau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                jPanel1.setBackground(new java.awt.Color(204, 204, 255));
                jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel2.setText("TG đi");

                jLabel_ThoiGianDi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel_ThoiGianDi.setText("07/11 06:00");

                jLabel_ThoiGianDen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel_ThoiGianDen.setText("07/11 06:00");

                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel5.setText("TG đến");

                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                jLabel6.setText("SL chỗ đặt");

                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel7.setText("SL chỗ trống");

                jLabel_SoLuongGheTrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel_SoLuongGheTrong.setText("jLabel8");

                jLabel_SoLuongDaDat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel_SoLuongDaDat.setText("jLabel8");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                                .addContainerGap(133, Short.MAX_VALUE)
                                                                                .addComponent(jLabel_SoLuongGheTrong)
                                                                                .addGap(20, 20, 20))
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(jLabel_ThoiGianDi,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(jLabel_ThoiGianDen,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addGap(6, 6, 6)
                                                                                                                                                                .addComponent(jLabel_SoLuongDaDat)))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                56,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(jLabel7)))
                                                                                .addContainerGap())));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(72, Short.MAX_VALUE)
                                                                .addComponent(jLabel_SoLuongGheTrong,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap())
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel2)
                                                                                                .addComponent(jLabel_ThoiGianDi))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel5)
                                                                                                .addComponent(jLabel_ThoiGianDen))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel6)
                                                                                                .addComponent(jLabel7))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel_SoLuongDaDat,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                35,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jPanel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel_tenTau,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel_tenTau)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                12,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));
        }// </editor-fold>//GEN-END:initComponents

        private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseClicked
                // TODO add your handling code here:
                ToanCuc.setLichTrinh(lichTrinhHienTai);

        }// GEN-LAST:event_formMouseClicked

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel_SoLuongDaDat;
        private javax.swing.JLabel jLabel_SoLuongGheTrong;
        private javax.swing.JLabel jLabel_ThoiGianDen;
        private javax.swing.JLabel jLabel_ThoiGianDi;
        private javax.swing.JLabel jLabel_tenTau;
        private javax.swing.JPanel jPanel1;
        // End of variables declaration//GEN-END:variables
}
