/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.*;
import java.awt.Image;
import java.net.URL;
import javax.swing.*;
import javax.swing.ImageIcon;

/**
 *
 * @author 84335
 */
public class TrangChu_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu_JPanel
     */
    public TrangChu_JPanel() {
        initComponents();
        setVisible(true);
        setBounds(0, 0, 1186, 748);
        
//        URL image_TrangChu = TrangChu_JPanel.class.getResource("/pic/icon/hinhnenTrangChu.png");
//        ImageIcon img_TrangChu = new ImageIcon(image_TrangChu);
//        Image scaled_TrangChu = img_TrangChu.getImage().getScaledInstance(1186, 748, Image.SCALE_SMOOTH);
//        img_TrangChu = new ImageIcon(scaled_TrangChu);
//        lbl_IConTrangChu.setIcon(img_TrangChu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_IConTrangChu = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 51, 0));
        setMinimumSize(new java.awt.Dimension(1186, 843));
        setPreferredSize(new java.awt.Dimension(1536, 850));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_IConTrangChu.setPreferredSize(new java.awt.Dimension(1355, 860));
        add(lbl_IConTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1186, 748));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_IConTrangChu;
    // End of variables declaration//GEN-END:variables
}
